### ISSUE TITLE
Upload Photo

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/app#129]
# Description
create feature for
- [x] upload photo

endpoint: `api/v1/user/photo`
payload: `image_data: something`
require `Authorization`
allowed format; `.jpg .jpeg .png`
<br />

# Type
- [x] feature
- [ ] bug

<br />

**Comment by andy-shi88** [comment]
what's the state of this issue @akbarrg ?

**Comment by akbarrg** [comment]
@andy-shi88 in progress
