### ISSUE TITLE
Redesign - Login Screen

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/app#15]
# Description
Now we should implement multiple register and login type
- [ ] display username and password field as the main login
- [ ] user should be able to choose between login with `facebook`, '`twitter`, and `google`

implementation come after this.
Note: there should be a small link to navigate user to register screen.

<br />

# Type
- [x] tweak
- [ ] bug

<br />

**Comment by hanalaydrus** [comment]
@andy-shi88 how about the newsletter button?

**Comment by andy-shi88** [comment]
for now let's ommit that. we'll find a proper place for that little button later. :+1:  cool? @hanalaydrus 
and for the social login  use each of social their logo would be cool, 
and this would be the screen that pop up after splash screen

**Comment by hanalaydrus** [comment]
@andy-shi88 I think I will change the validator of login to disable the button. Is it okay?

**Comment by andy-shi88** [comment]
yup, sure @hanalaydrus
