### ISSUE TITLE
re-design login using phone number

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/app#159]
# Description
re-design login using phone number

<br />

# Type
- [ ] feature
- [x] tweak

<br />

**Comment by akbarrg** [comment]
@andy-shi88 we are using account-kit, it's looks nice, so I think that we do not need to styling this account-kit component anymore, but if you have any concern about the style, please notify me to update it.

![screenshot_1504790915](https://user-images.githubusercontent.com/20442343/30165683-24d2e842-940b-11e7-9469-10f635ba01c2.png)

**Comment by andy-shi88** [comment]
ok then, thanks for checking it out @akbarrg  👍
