### ISSUE TITLE
Registration Bug

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/app#202]
# Description

The social registration didn't save `social_id` to the backend.

possible issue is we all use `RegisterEmail` container after getting all data needed from social registration.
I see that in `RegisterEmail` action there is no `social_id` being passed in the request.

another issue:
- do we still need to fill `password` using social registration? I figured this was originaly removed, and now it's there.
   

<br />

# Type
- [ ] feature
- [x] bug

<br />

**Comment by andy-shi88** [comment]
@akbarrg  what do you think?

**Comment by akbarrg** [comment]
@andy-shi88 Yes we do, we need to fill password field

**Comment by andy-shi88** [comment]
why is that? if it's constraint from backend I can tweak that part. but is there another reason? @akbarrg
