### ISSUE TITLE
Scene - Speaker List

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/app#26]
# Description
On User click on speker button on #22 

user should see list of attending speakers
- [x] show picture, first name, and last name of speaker
- [x] each speaker should be clickable
- [ ] on Clicked user should see a `modal` scene pop up showing summary of speakers

<br />

# Type
- [x] feature
- [ ] bug

<br />

**Comment by hanalaydrus** [comment]
@andy-shi88 Mr.Andy does the speaker has profile picture? What data should I show on the list? Just name?

**Comment by andy-shi88** [comment]
@hanalaydrus yup, they will have profile picture, prepare a placeholder picture. it would look like 
```
------------------------------------------------------------------- 
|    picture      |          first name: ________________| 
|                     |          last name: ________________|
|                     |                                                            |
--------------------------------------------------------------------
```
when clicked, a `modal` should pop up, showing almost the same information, except, there will be summary of the speaker.

**Comment by hanalaydrus** [comment]
@andy-shi88 just to make sure, so it's only profile-picture, first-name, and last-name?

**Comment by andy-shi88** [comment]
@hanalaydrus yap :laughing:

**Comment by hanalaydrus** [comment]
@andy-shi88 Mr.Andy can I share some of my thoughts? I think it will looks better if we didn't put the label 'first name' and 'last name'. I have three idea.
1. Use list view, the first line is full name and the second line is a little peek of the summary. But it looks like chat.
![image](https://user-images.githubusercontent.com/9986141/29028331-1ed701e6-7bae-11e7-8722-7e81d3120337.png)


2. Use list view, the first line is full name and the second line is the speaker job. But I didn't see any job data on user?
![image](https://user-images.githubusercontent.com/9986141/29028229-c959cd16-7bad-11e7-89c7-7998b5463b49.png)

3. Use card, and the summary is extendable.
Something like this but not as complicated as this. 
https://s-media-cache-ak0.pinimg.com/originals/f9/92/a8/f992a836560534266f4088dca44cedc5.gif

**Comment by andy-shi88** [comment]
@hanalaydrus  looks cool, I can add more data on speaker if you need them, and displaying job and is a good idea. I'll add the job data ASAP. for now you can go with your idea with some dummy or hard coded data. :+1:
