### ISSUE TITLE
Fix logout and login

### ISSUE THREAD

**Issue by akbarrg** [devsummit/app#260]
# Description
When user logout from app, user can not login again.

- [ ] check flow from logout.
- [ ] remove async storage when log out.

<br />

# Type
- [x] bug

<br />

**Comment by akbarrg** [comment]
I have tried about the logout, and the error is coming from refresh toke listener on push notification. @caudaganesh maybe you can take over this ticket. Thanks

**Comment by caudaganesh** [comment]
okay @akbarrg
