### ISSUE TITLE
Fix bank name on confirm payment.

### ISSUE THREAD

**Issue by akbarrg** [devsummit/app#275]
# Description
Please fix bank name and total, depends on what payment method that user choose before

![screenshot_1506311869](https://user-images.githubusercontent.com/20442343/30791941-a22f0ad6-a1e0-11e7-96a8-e51368622a4f.png)

<br />

Please check va_number, if there is no va_number, server will send redirect url, make it possible to redirect from our app.

<br />

# Type
- [x] bug

<br />

**Comment by andy-shi88** [comment]
@arnazmursidp 
here for the information of internet banking payment, we don't provide `va_number` from backend, instead we provide link for compleiting payment, but it's still in `va_number` field of the response.
display the link for internet banking, and make them clickable to oopen webview
for `bca_klikbca` though you may need to display the `merchant_code` you may ask from @akbarrg  for development merchant code.

**Comment by arnazmursidp** [comment]
okay i'll try to do it @andy-shi88

**Comment by andy-shi88** [comment]
great. if you have any question ask me or @akbarrg  here @arnazmursidp

**Comment by arnazmursidp** [comment]
okaay! @andy-shi88
