### ISSUE TITLE
Remove default phone number

### ISSUE THREAD

**Issue by mul14** [devsummit/app#326]
# Description
Doesn't make sense put someone's phone number as default input.

<br />

# Type
- [ ] feature
- [x] bug

<br />

**Comment by denisenricohasyim93** [comment]
it still generate random number,  maybe i can help this
![screen shot 2017-10-02 at 1 55 24 pm](https://user-images.githubusercontent.com/26061493/31066771-5fe43fc2-a779-11e7-9e2e-b3e0790138bd.png)
