### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/app#420]
# Description
the feedback web is available now, please implment it into the mobile:
just some button, redirect to (open chrome or webview) for submitting review

link `https://devsummit.io/feedback.html`

<br />

# Type
- [x] feature
- [ ]  bug

<br />

**Comment by rendisaepulb** [comment]
can i take this issue mr @andy-shi88 ?

**Comment by andy-shi88** [comment]
yes please @rendisaepul  👍

**Comment by andy-shi88** [comment]
give me some ETA 😄 @rendisaepul

**Comment by rendisaepulb** [comment]
maybe about 1 hours :)

**Comment by andy-shi88** [comment]
great 👍
