### ISSUE TITLE
Download speaker files.

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/app#428]
# Description
user should be able to browse to speaker and download their material if exist.

<br />

# Type
- [x] feature
- [ ] bug

<br />

**Comment by andy-shi88** [comment]
this should also apply when logged in as speaker, there should be file available now, log in as speaker. I should be able to download my file when click on the file.

**Comment by andy-shi88** [comment]
@arnazmursidp

**Comment by arnazmursidp** [comment]
oh okay i'll try to fetch the document mr @andy-shi88
