### ISSUE TITLE
redeem referal code and free pass

### ISSUE THREAD

**Issue by kru** [devsummit/app#458]
# Description
_After register I should be able to redeem free pass (after getting 10 referrals) and send referral code_
<br />

# Type
- [x] feature

<br />

**Comment by akbarrg** [comment]
![screenshot_1507910573](https://user-images.githubusercontent.com/20442343/31556286-86883e82-b06e-11e7-9b08-8adc5627a430.png)

Can we use this? or you want to create new? @arnazmursidp 
cc: @kru

**Comment by kru** [comment]
Nice design there, sure we will use your design @akbarrg
