### ISSUE TITLE
Improvement on order detail

### ISSUE THREAD

**Issue by akbarrg** [devsummit/app#547]
# Description

- [ ] Move ticket label (e.g pending) above order ID.
- [ ] Delete title ticket(e.g full) and price.
- [ ] Change date format to DD/MMM/YYYY
- [ ] Change amount to badge
- [ ] Total price uppercase && change price color to PRIMARY COLOR
- [ ] Delete mandiri logo
- [ ] Add download account reference above of payment proff image.
- [ ] Add artwork image no photos uploaded above of upload payment proof button.
- [ ] Fix text on upload payment proof

![screenshot_1508755912](https://user-images.githubusercontent.com/20442343/31886402-54d76018-b81e-11e7-90c1-3d790c0c737e.png)

<br />

# Type
- [x] tweak

<br />

**Comment by arnazmursidp** [comment]
![screenshot_2017-10-24-15-17-48](https://user-images.githubusercontent.com/19486285/31932029-44c31904-b8cf-11e7-875c-bc14ace76d6c.png)
![screenshot_2017-10-24-15-17-51](https://user-images.githubusercontent.com/19486285/31932030-44fb9df6-b8cf-11e7-8aa9-6e37e6d9e3c0.png)
![screenshot_2017-10-24-15-18-10](https://user-images.githubusercontent.com/19486285/31932032-4535e9fc-b8cf-11e7-8e09-e15b645339f2.png)
