### ISSUE TITLE
Order Payment

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/app#98]
# Description
Create feature for paying the order.
- should be a checkout button on order list
- when clicked, it will send request to register payment
- on success button will change to `confirm payment`
- on click `confirm payment` user should send a request to backed aasking for payment check, backend will tell if payment is paid or not.

<br />

# Type
- [x] feature

<br />

**Comment by andy-shi88** [comment]
let's create the mockup for this first: the backend is on about 80% finished. @caudaganesh

**Comment by caudaganesh** [comment]
working on it sir
